name: etkinlik
description: "Bilgisayar Uygulamalari 1 Projesi"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  # Google
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.6.11
  google_fonts: ^6.2.1

  # Flutter
  flutter:
    sdk: flutter

  # Riverpod
  flutter_riverpod: ^2.5.1

  # Helper
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  map_location_picker: ^1.2.8+3
  uuid: ^4.4.0
  intl: ^0.19.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/gif/
    - assets/image/
